SET IDENTITY_INSERT [dbo].[Schedule] ON
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (20, N'1st', 2, 480, 525)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (22, N'HomeRoom', 2, 571, 615)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (23, N'3rd', 2, 616, 660)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (24, N'4th', 2, 661, 705)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (25, N'Lunch', 2, 706, 750)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (26, N'5th', 2, 751, 795)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (27, N'6th', 2, 796, 840)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (28, N'7th', 2, 841, 885)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (31, N'8th', 2, 886, 930)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (44, N'2nd', 2, 526, 570)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (45, N'Period 1', 5, 480, 540)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (46, N'Period 2', 5, 540, 600)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (47, N'Period 3', 5, 600, 660)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (48, N'Period 4', 5, 660, 720)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (49, N'Lunch', 5, 720, 780)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (50, N'Period 5', 5, 780, 840)
INSERT INTO [dbo].[Schedule] ([Id], [Label], [SchoolId], [From], [To]) VALUES (51, N'Period 6', 5, 840, 900)
SET IDENTITY_INSERT [dbo].[Schedule] OFF
